// import RootLayoutClient from './RootLayoutClient';

import RootLayoutClient from "./RoutLayoutClient";

export const metadata = {
  title: "Consti-on-all",
  description: "Generated by seguros-constitucion",
};

export default function RootLayout({ children }) {
  return <RootLayoutClient>{children}</RootLayoutClient>;
}

